---
- name: Deploy Docker Containers
  hosts: localhost
  vars_files:
    - secrets.yml  # Load encrypted secrets (e.g., db_url)

  roles:
    - backend  # Role for backend tasks
    - frontend  # Role for frontend tasks
