---
- name: Deploy Docker Containers
  hosts: localhost
  vars_files:
    - secrets.yml  # Load encrypted variables (contains db_url)
  
  tasks:

    # 1. Create backend environment file dynamically
    - name: Create backend environment file dynamically
      shell: echo MONGO_URI={{ db_url }} > /home/aasmaan/Desktop/WebDevH/paytm/backend/.env
      args:
        chdir: "{{ playbook_dir }}"  # Ensure correct directory is used to run the shell command

    # 2. Build backend Docker image
    - name: Build backend Docker image
      docker_image:
        build:
          path: /home/aasmaan/Desktop/WebDevH/paytm/backend  # Absolute path to backend directory
        name: aasmaan1/backend
        tag: latest
      when: build_backend | default(true)
      become: yes  # Use sudo if needed

    # 3. Push backend Docker image to DockerHub
    - name: Push backend Docker image to DockerHub
      docker_image:
        name: aasmaan1/backend
        tag: latest
        push: yes
      when: build_backend | default(true)
      become: yes  # Use sudo if needed

    # 4. Create frontend environment file dynamically (if needed)
    - name: Create frontend environment file dynamically
      shell: echo FRONTEND_ENV={{ frontend_var }} > /home/aasmaan/Desktop/WebDevH/paytm/frontend/.env
      args:
        chdir: "{{ playbook_dir }}"  # Ensure correct directory is used to run the shell command

    # 5. Build frontend Docker image
    - name: Build frontend Docker image
      docker_image:
        build:
          path: /home/aasmaan/Desktop/WebDevH/paytm/frontend  # Absolute path to frontend directory
        name: aasmaan1/frontend
        tag: latest
      when: build_frontend | default(true)
      become: yes  # Use sudo if needed

    # 6. Push frontend Docker image to DockerHub
    - name: Push frontend Docker image to DockerHub
      docker_image:
        name: aasmaan1/frontend
        tag: latest
        push: yes
      when: build_frontend | default(true)
      become: yes  # Use sudo if needed

    # 7. Pull Docker images (from DockerHub)
    - name: Pull Docker images (from DockerHub)
      shell: docker-compose pull
      args:
        chdir: "{{ playbook_dir }}"  # Use playbook directory for Docker Compose

    # 8. Start Docker containers (using images from DockerHub)
    - name: Start Docker containers (using images from DockerHub)
      shell: docker-compose up -d
      args:
        chdir: "{{ playbook_dir }}"  # Use playbook directory for Docker Compose
